-- 1) COLUMNS LIKE YEAR_ID AND MONTH_ID AREN'T NEEDED WHEN YOU ALREADY HAVE THOSE INFO IN ORDERDATE

ALTER TABLE SALES
DROP COLUMN YEAR_ID,
DROP COLUMN MONTH_ID;

-- 2) MOST OF THE TIME PORTION OF 'ORDERDATE' IS 00:00:00, WHICH IS NOT USEFUL FOR ANALYSIS

ALTER TABLE SALES
MODIFY COLUMN ORDERDATE DATE
;

UPDATE SALES
SET ORDERDATE = DATE(ORDERDATE)
;

-- 3) SALES = QUANTITYORDERED * PRICEEACH, DROPPING THE COLUMN BECAUSE IF NEEDED, WOULD CALCULATE AGAIN

ALTER TABLE SALES
DROP COLUMN SALES;