
-- 1) TOP PRODUCT BY REVENUE (COUNTRY/YEAR)

SELECT COUNTRY, PRODUCTLINE, YEAR_ID, REVENUE FROM (
	SELECT COUNTRY, PRODUCTLINE, YEAR_ID, REVENUE, DENSE_RANK() OVER(PARTITION BY COUNTRY, YEAR_ID ORDER BY REVENUE DESC) AS ordering
    FROM ( 
		SELECT DISTINCT
			COUNTRY, PRODUCTLINE, YEAR_ID, SUM(SALES) AS REVENUE
		FROM
			SALES
		GROUP BY 1 , 2 , 3
) a) a WHERE ordering = 1
ORDER BY COUNTRY, PRODUCTLINE, YEAR_ID
;

-- 2) HIGHEST REVENUE CITY PER COUNTRY

SELECT COUNTRY, CITY, REVENUE FROM (
SELECT *, ROW_NUMBER() OVER(PARTITION BY COUNTRY ORDER BY REVENUE DESC) AS ORDERING 
FROM (
	SELECT DISTINCT
		COUNTRY, CITY, SUM(SALES) AS REVENUE
	FROM
		SALES
	GROUP BY COUNTRY , CITY
	ORDER BY COUNTRY , REVENUE DESC) A) A
WHERE ORDERING = 1
;

-- 3) PRODUCTS THAT ARE OFTEN BOUGHT TOGETHER

WITH prods AS (
SELECT 
    ordernumber, productcode
FROM
    sales s
WHERE
    STATUS = 'Shipped'
ORDER BY ordernumber
)

SELECT 
    p.productcode, s.productcode, COUNT(*) AS times_sold
FROM
    prods p
        JOIN
    prods s ON p.productcode < s.productcode
        AND p.ordernumber = s.ordernumber
GROUP BY p.productcode , s.productcode
HAVING COUNT(*) > 1
ORDER BY cnt DESC
;

-- 4) QUARTERLY REVENUE PER COUNTRY

SELECT COUNTRY, YEAR(ORDERDATE) AS YEAR, QTR_ID AS QUARTER, GROUP_CONCAT(DISTINCT MONTHNAME(ORDERDATE) ORDER BY MONTH(ORDERDATE)) AS MONTHS, SUM(QUANTITYORDERED * PRICEEACH) AS REVENUE FROM SALES
GROUP BY 1,2,3
ORDER BY COUNTRY, YEAR, REVENUE DESC;

-- 5) MOST POPULAR PRODUCTLINE ACROSS COUNTRIES

WITH PRODREVENUE AS (
SELECT 
    COUNTRY,
    PRODUCTLINE,
    SUM(QUANTITYORDERED * PRICEEACH) AS REVENUE
FROM
    SALES
GROUP BY COUNTRY , PRODUCTLINE
ORDER BY REVENUE DESC
), CONT_FAM_PRODS AS (
-- I) COUNTRIES AND THEIR MOST SOLD PRODUCTS
SELECT COUNTRY, PRODUCTLINE FROM (
SELECT COUNTRY, PRODUCTLINE, DENSE_RANK() OVER(PARTITION BY COUNTRY ORDER BY REVENUE DESC) AS ORDERING FROM PRODREVENUE
) A
WHERE ORDERING = 1)
-- II) POPULAR PRODUCTLINES (THAT ARE THE TOP SELLING ACROSS MOST COUNTRIES)-- 
SELECT 
    PRODUCTLINE, COUNT(*) AS POPULARITY
FROM
    CONT_FAM_PRODS
GROUP BY PRODUCTLINE
ORDER BY POPULARITY DESC
;

-- 6) RFM (RECENCY, FREQUENCY, MONETARY) ANALYSIS

WITH RECENCY AS (
SELECT *, NTILE(5) OVER(ORDER BY RECENTDATE) AS Recency FROM (
SELECT CUSTOMERNAME, ABS(DATEDIFF(MAX(ORDERDATE), (SELECT MAX(ORDERDATE) FROM SALES))) AS RECENTDATE FROM SALES
WHERE STATUS = "Shipped"
GROUP BY CUSTOMERNAME
) a
), FREQUENCY AS (
SELECT *, NTILE(5) OVER(ORDER BY FREQ DESC) AS FREQUENCY FROM (
SELECT CUSTOMERNAME, COUNT(*) AS FREQ FROM SALES
WHERE STATUS = "Shipped"
GROUP BY CUSTOMERNAME
) A
), MONETARY AS (
SELECT *, NTILE(5) OVER(ORDER BY REVENUE DESC) AS MONETARY FROM (
SELECT CUSTOMERNAME, SUM(QUANTITYORDERED*PRICEEACH) AS REVENUE FROM SALES
WHERE STATUS = "Shipped"
GROUP BY CUSTOMERNAME
) A
)
SELECT R.CUSTOMERNAME AS TOP_CUSTOMERS FROM RECENCY R 
JOIN FREQUENCY F ON F.CUSTOMERNAME = R.CUSTOMERNAME
JOIN MONETARY M ON F.CUSTOMERNAME = M.CUSTOMERNAME
WHERE RECENCY = FREQUENCY AND FREQUENCY = MONETARY AND RECENCY = 1
ORDER BY RECENCY
;

-- 7) ANNUAL REVENUE PER COUNTRY FROM 2003 TO 2005

SELECT 
    COUNTRY,
    CEIL(SUM(CASE
                WHEN YEAR(ORDERDATE) = 2003 THEN QUANTITYORDERED * PRICEEACH
                ELSE 0
            END)) AS '2003',
    CEIL(SUM(CASE
                WHEN YEAR(ORDERDATE) = 2004 THEN QUANTITYORDERED * PRICEEACH
                ELSE 0
            END)) AS '2004',
    CEIL(SUM(CASE
                WHEN YEAR(ORDERDATE) = 2005 THEN QUANTITYORDERED * PRICEEACH
                ELSE 0
            END)) AS '2005'
FROM
    SALES
GROUP BY COUNTRY
ORDER BY COUNTRY

